---

- hosts: all
  become: yes
  tasks:
  - name: Install Zabbix-Agent on CentOS
    yum:
       name=zabbix-agent
       state=latest
    when:
       ansible_os_family == "RedHat"
    notify:
       zabbix-agent systemd
  -  name: Install Zabbix-Agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
